{%- import 'macros/merge.yaml' as merge %}
{%- import 'macros/integration.yaml' as integration %}
{%- import 'macros/env-file.yaml' as env_file %}
{%- import 'macros/merge-env-files.yaml' as merge_env_files %}
{%- import 'macros/debug-env.yaml' as debug_env %}
groups:
  - name: test
    jobs:
      - batch-builds-together
      - integration
  - name: stage
    jobs:
      {%- for project in projects %}
      - stage-{{ project.name }}
      {%- endfor %}
      - batch-uploads-together
      - create-staging-env-files
  - name: all
    jobs:
      {%- for project in projects %}
      - stage-{{ project.name }}
      {%- endfor %}
      - batch-builds-together
      - integration
      - batch-uploads-together
      - create-staging-env-files

resources:
  - name: busywork
    type: git
    source:
      uri: https://github.com/qiime2/busywork
      branch: master

  - name: throttle-timer
    type: time
    source:
      interval: 10m

  - name: docs-source
    type: git
    check_every: 2m
    source:
      uri: https://github.com/{{ defaults.github_org }}/docs
      branch: {{ defaults.release_branch }}

  - name: environment-files
    type: git
    check_every: 10m
    source:
      uri: https://github.com/qiime2/environment-files
      branch: py38
      username: ((github_user))
      password: ((github_pass))

  {%- for project in projects %}
  - name: {{ project.name }}-{{ project.release }}-test-channel
    type: conda-channel
    check_every: 10m
    source:
      pkg_name: {{ project.name }}
      uri: https://packages.qiime2.org/qiime2
      channel: {{ project.test_channel }}
      regex: ^{{ project.release|replace('.', '\.') }}\.[0-9]\.dev1+
      matched: [osx-64, linux-64]

  - name: {{ project.name }}-{{ project.release }}-staging-channel
    type: conda-channel
    check_every: 10m
    source:
      pkg_name: {{ project.name }}
      uri: ((staging_uri))
      channel: {{ project.staging_channel }}
      user: ((staging_user))
      pass: ((staging_pass))
      regex: ^{{ project.release|replace('.', '\.') }}\.[0-9]\.dev1+
      matched: [osx-64, linux-64]
  {% endfor %}
jobs:
  {%- for project in projects %}
  - name: stage-{{ project.name }}
    public: true
    plan:
      - get: {{ project.name }}-{{ project.release }}-test-channel
        trigger: true
        passed: [integration]
      - put: {{ project.name }}-{{ project.release }}-staging-channel
        params:
          from: {{ project.name }}-{{ project.release }}-test-channel
  {% endfor %}
  - name: batch-builds-together
    public: true
    build_logs_to_retain: 50
    plan:
      - get: throttle-timer
        trigger: true
      {%- for project in projects %}
      - get: {{ project.name }}-{{ project.release }}-test-channel
      {%- endfor %}

  - name: integration
    public: true
    max_in_flight: 1
    plan:
      - get: busywork
      - get: environment-files
      - get: docs-source
        trigger: true
      {%- for project in projects %}
      - get: {{ project.name }}-{{ project.release }}-test-channel
        trigger: true
        passed: [batch-builds-together]
      {%- endfor %}
      - aggregate:
        - task: integration-linux
          config:
            {{- integration.make_linux_config(projects, sorted_projects, defaults)|indent(12) }}
          on_failure:
            task: debug-environment
            config:
              {{- debug_env.make_linux_config(defaults)|indent(14) }}
        - task: integration-darwin
          config:
            {{- integration.make_darwin_config(projects, sorted_projects, defaults)|indent(12) }}
          on_failure:
            task: debug-environment
            config:
              {{- debug_env.make_darwin_config(defaults)|indent(14) }}
      - task: merge-and-commit-env-yaml
        config:
          {{- merge_env_files.make_config("unprocessed", defaults)|indent(10) }}
      - put: environment-files
        params:
          repository: updated-environment-files
          rebase: true

  - name: batch-uploads-together
    public: true
    build_logs_to_retain: 50
    plan:
      - get: throttle-timer
        trigger: true
      {%- for project in projects %}
      - get: {{ project.name }}-{{ project.release }}-staging-channel
        passed: [stage-{{ project.name }}]
      {%- endfor %}

  - name: create-staging-env-files
    serial_groups: [create-env-files]
    public: true
    plan:
      - get: busywork
      - get: environment-files
      {%- for project in projects %}
      - get: {{ project.name }}-{{ project.release }}-staging-channel
        trigger: true
        passed: [batch-uploads-together]
      {%- endfor %}
      - aggregate:
        - task: staging-env-file-linux
          config:
            {{- env_file.make_linux_config(projects, defaults, "staging-channel")|indent(12) }}
        - task: staging-env-file-darwin
          config:
            {{- env_file.make_darwin_config(projects, defaults, "staging-channel")|indent(12) }}
      - task: merge-and-commit-env-files
        config:
          {{- merge_env_files.make_config("staging", defaults)|indent(10) }}
      - put: environment-files
        params:
          repository: updated-environment-files
          rebase: true

resource_types:
  - name: conda-channel
    type: docker-image
    source:
      repository: quay.io/qiime2/conda-channel-resource
